widgets:
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: Nofated
        # Author title
        author_title: 'May we will never be together, but forever you are in my heart.'
        # Author's current location
        location: Beijing, China
        # URL or path to the avatar image
        # avatar: https://pic.rmb.bdstatic.com/bjh/8b98d9798b6997e61a19d49503845644.png
        avatar: https://img.9595095.xyz/avatars/-1.png
        # Whether show the rounded avatar image
        avatar_rounded: false
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: 'https://space.bilibili.com/351951550'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'https://github.com/Nofated095'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/nofated095'
            Telegram:
                icon: fab fa-telegram
                url: 'https://t.me/Nofated'
            # QQ:
                # icon: fab fa-qq
                # url: 'tencent://message/?uin=2032025551&Menu=yes'
            Email:
                icon: fas fa-envelope
                url: 'mailto:nofated095@outlook.com'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: toc
        # Whether to show the index of each heading
        index: true
    -
        position: left
        type: archives
    -
        position: left
        type: categories
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: tags
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: toc
        # Whether to show the index of each heading
        index: true
        # Whether to collapse sub-headings when they are out-of-view
        collapsed: true
        # Maximum level of headings to show (1-6)
        depth: 3
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: recent_posts
    # Recommendation links widget configurations
    -
        position: right
        type: links
        links:
            BMCLAPI: 'http://bmclapidoc.bangbang93.com/'
            Jenkins of HMCL: 'https://ci.huangyuhui.net/'
            Microsoft Docs: 'https://docs.microsoft.com/zh-cn/'
            萌ICP备20214514号: 'https://icp.gov.moe/?keyword=20214514'
            Travelling: 'https://travellings.link/'
    # Recent posts widget configurations
    # Tags widget configurations